<a href="https://colab.research.google.com/github/Juniormoraess/Algebra-Linear-Computacional/blob/master/Reflex%C3%B5es%20de%20Householder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import numpy as np
import time
import matplotlib.pyplot as plt
from math import hypot
%matplotlib inline

def D_Matriz(m4):
    A_copy = np.delete(m4, 0, 0)
    A_copy = np.delete(A_copy, 0, 1)
    return A_copy

def isTriangular(A):
    n_lin, n_col = np.shape(A)
    
    for i in range(n_lin):
        for j in range(n_col):
            if i > j:
                if A[i,j] != 0:
                    return False
    return True

def Adiciona_Id(A,tam):
    nlin, ncol = np.shape(A)
    Id = np.identity(tam)

    for i in range(tam - nlin, tam):
        for j in range(tam - nlin, tam):
            Id[i, j] = A[i - (tam - nlin)][j - (tam - nlin)]
            
    return Id

def Householder(A):
    Identidade = np.identity(len(A), dtype=float)
    
    #Pegando a primeira coluna de A
    #Calculando a norma da primeira coluna
    a = np.linalg.norm(A.transpose()[0])

    #Criação do vetor "e"
    e = np.eye(len(A), 1, 0, dtype=float)


    #Multiplicação de "a" por "e"
    a_e = a * e

    #Criação do vetor "u"
    u = (A.transpose()[0] - a_e.T)

    #Criação do vetor "v"
    v = (u / np.linalg.norm(u)).T

    #Criação do "Q1"
    Q = Identidade - 2 * (v @ v.T)
    Q = Adiciona_Id(Q, lin_a)

    return Q

#Para gerar o tempo médio de execução
n_testes = 3 

#Guarda o tempo de execução das Reflexões de Householder
exec_time_hh = np.zeros(5) 

A = np.random.randint(-999,999,(5, 5))
A_original = A
lin_a, col_a = np.shape(A)

#Produto Q @ A:
Q = Householder(A)
Q_final = Q.T

start_time = time.time()

while isTriangular(Q @ A) != True:
    A = D_Matriz(Q @ A)
    Q = Householder(A)
    Q_final = Q.T @ Q_final
    break

end_time = time.time()
    
exec_time = (end_time - start_time) / n_testes
exec_time_hh[0] = round(exec_time, 6)

print('\nTempo de execução: %.6fs' % exec_time_hh[0])

print('\nMatriz A: \n', A_original)

print('\nMatriz Q: \n', Q.round(2))
print()

print('\nMatriz R:\n',(Q_final @ A_original).round(2))
print()

R = Q_final.T @ A_original
print('\nMatriz QR:\n', (Q_final @ R).round(2))
print()


Tempo de execução: 0.002810s

Matriz A: 
 [[-105 -589  764  381 -534]
 [-362  916  385 -859  213]
 [  18  -17 -950   65 -369]
 [ 788  602  288  973  541]
 [-493  378  138  819  757]]

Matriz Q: 
 [[ 1.    0.    0.    0.    0.  ]
 [ 0.    0.86 -0.02  0.13  0.5 ]
 [ 0.   -0.02  1.    0.02  0.07]
 [ 0.    0.13  0.02  0.88 -0.46]
 [ 0.    0.5   0.07 -0.46 -0.73]]


Matriz R:
 [[ 1003.19    17.91   -77.53   633.06    25.35]
 [   -0.    1300.47   112.07   -98.71   866.82]
 [   -0.      -0.    -936.05   158.68  -310.14]
 [    0.       0.     884.59   173.26  -287.93]
 [   -0.       0.    -243.21 -1427.95  -633.48]]


Matriz QR:
 [[-105. -589.  764.  381. -534.]
 [-362.  916.  385. -859.  213.]
 [  18.  -17. -950.   65. -369.]
 [ 788.  602.  288.  973.  541.]
 [-493.  378.  138.  819.  757.]]

