<a href="https://colab.research.google.com/github/Juniormoraess/Algebra-Linear-Computacional/blob/master/Rota%C3%A7%C3%A3o%20de%20Givens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import numpy as np
import time
import matplotlib.pyplot as plt
from math import hypot
%matplotlib inline

def RotacaoGivens(matriz):
    n_linhas,n_colunas = np.shape(matriz)
    Q = np.identity(n_linhas)
    R = np.copy(matriz)
    (linhas, colunas) = np.tril_indices(n_linhas, -1, n_colunas)
    
    for (lin,col) in zip(linhas,colunas): 
      if R[lin,col] != 0:
        (c,s) = calcular_rotacao(R[col,col],R[lin,col])

        G = np.identity(n_linhas)
        G[[col,lin],[col,lin]] = c 
        G[lin,col] = s
        G[col,lin] = -s
                        
        R = np.dot(G,R)
        Q = np.dot(Q, G.T)
        R_triangular = np.triu(R)
            
    return (Q,R_triangular)

#Calcula os novos valores do cosseno e seno
def calcular_rotacao(a,b): 
    r = hypot(a,b)
    c = a/r
    s = -b/r
    return(c,s)

#Para gerar o tempo médio de execução
n_testes = 3 

#Para gerar o tempo médio de execução
exec_time_gr = np.zeros(5) 

A = np.random.randint(-999,999,(5,5))
A_original = A
lin_a, col_a = np.shape(A)

start_time = time.time()

for _ in range(n_testes):
    Q,R = RotacaoGivens(A)

end_time = time.time()

exec_time = (end_time - start_time) / n_testes
exec_time_gr[0] = round(exec_time, 6)

print('\nTempo de execução: %.6fs' % exec_time_gr[0])
print('\nMatriz A:\n', A)
print('\nMatriz Q:\n', Q)
print('\nMatriz R:\n', R)
print('\nMatriz QR:\n', Q@R)


Tempo de execução: 0.004373s

Matriz A:
 [[-849 -157  210  250  258]
 [ 665  531   17 -808  284]
 [-279 -244 -815 -994 -226]
 [-338  -32 -589  382 -246]
 [ 852  931 -409  256  403]]

Matriz Q:
 [[-0.588532    0.67427477  0.29685419 -0.30570803  0.1319235 ]
 [ 0.46098208  0.16444482  0.07523881 -0.68325983 -0.53660838]
 [-0.19340451 -0.1050109  -0.78536583 -0.48726823  0.31198973]
 [-0.23430367  0.32021717 -0.49287228  0.39007655 -0.66893942]
 [ 0.59061162  0.63619582 -0.215625    0.22384942  0.38707892]]

Matriz R:
 [[1442.5723552   941.72884646  -61.68564071 -265.66986302  318.4422593 ]
 [   0.          589.13307474 -218.83485796  425.26720088  422.01117056]
 [   0.            0.         1082.18398929  550.59701278  309.79858571]
 [   0.            0.            0.         1166.30624677 -168.54336006]
 [   0.            0.            0.            0.          131.6817052 ]]

Matriz QR:
 [[-849. -157.  210.  250.  258.]
 [ 665.  531.   17. -808.  284.]
 [-279. -244. -815. -994. -226.]